### ISSUE TITLE
Get an error Model class sorl.thumbnail.models.KVStore doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.

### ISSUE THREAD

**Issue by taime** [dessibelle/sorl-thumbnail-serializer-field#10]

**Comment by taime** [comment]
I've get an error:
`Model class sorl.thumbnail.models.KVStore doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

Doing everything like you've said in instruction

**Comment by dessibelle** [comment]
I have never seen that myself, but I have not really been running sorl-thumbnail-serializer-field with the newest versions of sorl-thumnail. 

Try specifying `sorl-thumbnail==12.3` in your `requirements.txt` to force an older version.

**Comment by suckmybigdick** [comment]
> I have never seen that myself, but I have not really been running sorl-thumbnail-serializer-field with the newest versions of sorl-thumnail.
> 
> Try specifying `sorl-thumbnail==12.3` in your `requirements.txt` to force an older version.

dosen't work

**Comment by cllen** [comment]
> I have never seen that myself, but I have not really been running sorl-thumbnail-serializer-field with the newest versions of sorl-thumnail.
> 
> Try specifying `sorl-thumbnail==12.3` in your `requirements.txt` to force an older version.
it works perfectly!thanks!

**Comment by taime** [comment]
it's been a while ))
I think we can close this ticket, I don't have this problem now... may be it's fixed
