### ISSUE TITLE
Config Folder upload instead of CACHE

### ISSUE THREAD

**Issue by tagmetag** [dessibelle/sorl-thumbnail-serializer-field#9]
I want to upload on ONE folder with original image instead of uploading on CACHE folder. How can I do that.
<img width="1180" alt="nh ch p man hinh 2017-10-05 luc 12 40 11 sa" src="https://user-images.githubusercontent.com/19923843/31190616-cab5e86c-a965-11e7-97f5-809466a9899c.png">
Thanks in advance!

**Comment by dessibelle** [comment]
I would suggest you refer to the [sorl-thumbnail documentation](http://sorl-thumbnail.readthedocs.io/en/latest/reference/settings.html). If I understand your question correctly you don't want to thumbnails stored in the `cache` sub directory. That's a bitt odd IMO, as the files generated by sorl-thumbnail is to be considered to be cachable data derived from the original files uploaded (i.e. the can expire and will need to be regenerated when the original files or the thumbnail settings change.

That said, I believe it would be possible to change your `ImageField` (and perhaps sorl-thumbnail too) settings so that both fields will use the same directory.

---

I've re-read your question and am not quite sure if I'm understanding it. Please elaborate if my assumptions above are incorrect.

**Comment by tagmetag** [comment]
@dessibelle Thank you. You've understood my question correctly. I want to store photos like Instagram storing for User's Avatar. With a picture like: https://instagram.fbkk10-1.fna.fbcdn.net/t51.2885-19/s/15043476_153032251839318_238335899987869696_a.jpg, It's auto generated by dimension into URL like: https://instagram.fbkk10-1.fna.fbcdn.net/t51.2885-19/s320x320/15043476_153032251839318_238335899987869696_a.jpg or https://instagram.fbkk10-1.fna.fbcdn.net/t51.2885-19/s200x200/15043476_153032251839318_238335899987869696_a.jpg by URL difference in (s, s200x200, s320x320, ...). All about instagram avatar photos can be generated into many dimensions. So that is the reason I want to generate thumbnail into one folder. If i wrongly understand the solr-thumbnail. Please help me make it clear.
Thanks Dessibelle!

**Comment by dessibelle** [comment]
I think it's out of scope for sorl-thumbnail-serializer-field to handle that, as it simply takes an existing FileField from your models and let's you expose the images in different size though your REST API. If you wan't to change where the files are stored you'd have to resort to doing so in the configuration for `sorl-thumbnail` or `ImageField`. If it's a case of adding more than one thumbnail to and endpoint, simply add more than one `HyperlinkedSorlImageField` field to your model's serializer.

**Comment by congtoanle** [comment]
<b-nav-item-dropdown class="no_toggle" right>
    <span slot="text"><span class="badge top noti">99+</span>
    <svg class="earth_i" viewBox="0 0 1024 1024"><path class="path1" d="M874.038 149.962c-96.704-96.704-225.278-149.962-362.038-149.962s-265.334 53.258-362.038 149.962c-96.704 96.704-149.962 225.278-149.962 362.038s53.258 265.334 149.962 362.038c96.704 96.704 225.278 149.962 362.038 149.962s265.334-53.258 362.038-149.962c96.704-96.704 149.962-225.278 149.962-362.038s-53.258-265.334-149.962-362.038zM941.918 346.178c-9.989-17.987-35.050-26.512-67.853-37.661-35.182-11.957-47.608-48.122-61.994-89.997-12.49-36.35-25.398-73.874-56.069-97.238 83.898 52.584 149.733 131.406 185.915 224.896zM798.235 521.757c3.872 34.683 7.875 70.546-35.163 118.874-11.629 13.056-18.44 31.238-25.653 50.49-16.701 44.582-32.486 86.709-99.642 87.325-1.882-2.262-7.242-10.734-11.981-37.533-4.366-24.698-6.886-56.606-9.555-90.389-4.093-51.834-8.731-110.582-21.544-159.32-16.382-62.325-43.867-99.141-84.026-112.554-17.522-5.853-35.411-8.698-54.693-8.698-14.211 0-27.125 1.522-38.517 2.864-8.875 1.045-17.258 2.034-24.341 2.034 0 0-0.002 0-0.003 0-11.987 0-25.573 0-42.278-38.29-24.021-55.053-6.304-143.267 64.202-189.787 38.661-25.509 65.336-36.392 89.2-36.392 19.026 0 39.581 6.622 68.73 22.146 34.418 18.33 61.379 20.68 81.026 20.68 7.789 0 14.85-0.419 21.682-0.826 5.726-0.339 11.134-0.661 16.139-0.661 11.259 0 20.387 1.467 31.088 8.776 19.723 13.472 29.936 43.195 40.747 74.664 16.392 47.715 34.973 101.798 93.941 121.837 7.925 2.693 21.576 7.333 31.216 11.366-8.328 8.608-22.285 21.067-35.92 33.24-8.808 7.862-18.789 16.773-29.851 26.858-31.965 29.133-28.16 63.221-24.803 93.296zM51.25 508.070c5.52 0.992 11.493 2.141 17.605 3.446 28.776 6.141 42.235 11.686 48.117 14.798-2.706 5.277-8.187 13.056-11.81 18.195-12.669 17.976-28.435 40.349-22.437 64.984 4.046 16.618 0.632 37.032-5.248 55.883-16.994-48.005-26.277-99.624-26.277-153.378 0-1.314 0.038-2.618 0.050-3.93zM512 972.8c-175.379 0-328.173-98.494-406.014-243.062 13.422-25.554 38.314-82.054 26.68-131.547 0.806-4.97 9.248-16.95 14.349-24.186 13.874-19.688 31.141-44.189 18.35-70.152-8.976-18.222-32.957-30.534-80.181-41.17-10.939-2.464-21.594-4.47-30.65-6.019 27.424-228.090 222.107-405.464 457.466-405.464 80.776 0 156.749 20.918 222.83 57.582-16.33-7.134-31.154-8.266-43.014-8.266-6.523 0-12.957 0.382-19.176 0.752-6.085 0.362-12.374 0.734-18.645 0.734-14.542 0-32.682-1.742-56.958-14.67-37.056-19.734-64.808-28.155-92.795-28.155-34.635 0-69.744 13.414-117.397 44.856-41.197 27.181-72.229 68.779-87.381 117.133-14.779 47.166-13.2 95.418 4.448 135.867 20.824 47.728 48.336 69.013 89.203 69.014 0.003 0 0.003 0 0.006 0 10.090 0 19.923-1.158 30.333-2.386 10.482-1.235 21.32-2.512 32.525-2.512 13.869 0 26.094 1.926 38.472 6.061 22.488 7.512 39.082 32.701 50.728 77.008 11.648 44.31 16.098 100.638 20.021 150.334 3.274 41.454 6.366 80.61 13.176 110.126 4.136 17.923 9.494 31.538 16.379 41.621 10.283 15.058 25.032 23.35 41.526 23.35 45.269 0 81.429-14.594 107.47-43.374 21.659-23.934 32.722-53.466 41.613-77.194 5.245-14.003 10.67-28.482 15.941-34.402 58.219-65.373 52.203-119.258 47.813-158.603-3.226-28.888-3.285-39.123 8.408-49.781 10.864-9.904 20.741-18.722 29.454-26.499 18.568-16.576 31.984-28.554 41.397-38.83 6.464-7.058 21.603-23.584 17.395-44.28-0.037-0.184-0.088-0.358-0.126-0.539 17.558 48.701 27.154 101.174 27.154 155.851 0 254.086-206.714 460.8-460.8 460.8z"></path></svg>
    </span>
    <div class="drop_content large">
      <div class="tabs friend_re">
        <div class="header">
          <span>Notifications</span>
          <router-link to="/settings/" title="settings"><svg class="pull-right" role="img" viewBox="0 0 54 54"><use xlink:href="#settings_i"></use></svg></router-link>
        </div>
        <div class="tab-content">
          <ItemNotification/>
          <ItemNotification/>
          <ItemNotification/>
          <ItemNotification/>
          <ItemNotification/>
          <ItemNotification/>
        </div>
      </div>
        <a href="/" title="Mark as read">
            <div class="drop_below">Mark as read</div>
        </a>
        </div>
  </b-nav-item-dropdown>
This is Dropdown Components. It's in header bar. When I click on router-link to="/settings/". It load settings page but remain Dropdown opening.

**Comment by tagmetag** [comment]
1. Sorry I make confuse with this question: Images which generated in CACHE folder will be deleted in the future or it remains keep exist.
2. Do you know the way how to store photo like Instagram I said to you?

**Comment by dessibelle** [comment]
1. That depends on your cache settings. I assume they will be stored for as long as they are not deemed expired by the caching system. For these settings, please refer to the Django and sorl-thumbnail documentation. I'm not sure, but I believe the default behaviour is that cached items are removed from the filesystem once they expire.
1. Generating images on the fly from URL parameters like that is not something that's supported by HyperlinkedSorlImageField at the moment, as all fields on the serializer must be defined in the serializer class. Definitely something that would be fairly simple to implement with Django URL patterns and a thumbnail generation module such as sorl-thumbnail.

Frankly though, both or your questions are out of the scope of sorl-thumbnail-serializer-field though. Good luck with finding a solution!

**Comment by tagmetag** [comment]
Thank you very much!
